    const chapters = [
      {p:0.00, years:'2019 — 2022', title:'Every path starts <em>small.</em>', body:'Computer Engineering was the beginning: strong fundamentals, steady curiosity, and the first proof that the work could compound.', challenge:'Turn curiosity into engineering discipline.', growth:'A foundation strong enough to keep climbing.', proof:'First Class Distinction · 9.7 GPA final semester', kit:'Foundations · Problem solving'},
      {p:0.14, years:'Dec 2021 — May 2022', title:'Then the work became <em>real.</em>', body:'Freelancing introduced clients, deadlines and users. A three-app food-delivery solution and Cricwin Live Guru turned classroom skill into shipped product.', challenge:'Build for people who actually depend on the result.', growth:'Confidence through shipping and feedback.', proof:'Cricwin Live Guru · 25K+ Google Play installs', kit:'Flutter · Dart · Firebase · REST APIs'},
      {p:0.28, years:'Feb 2022 — Sep 2022', title:'Pressure started carrying <em>weight.</em>', body:'At World of Wealth, the work expanded from implementation into product judgment: taking a fintech mobile application from concept toward an MVP for investment rounds.', challenge:'Move from feature execution to concept-to-MVP ownership.', growth:'Product sense and stakeholder coordination.', proof:'Fintech app · Concept → MVP', kit:'Flutter · Product coordination · Delivery'},
      {p:0.42, years:'Sep 2022 — Apr 2023', title:'The road asked him to <em>lead.</em>', body:'KodeKrew turned individual output into team output. He led two Flutter developers across news, astrology and instant-delivery applications.', challenge:'Be accountable for more than your own code.', growth:'Leadership, coordination and broader system thinking.', proof:'Led a two-developer Flutter team', kit:'Live streaming · Places · Tracking · FCM'},
      {p:0.56, years:'Apr 2023 — Aug 2024', title:'Good code needed a <em>structure.</em>', body:'At Cropdata, he became the primary Flutter point of contact and pushed BLoC and Clean Architecture into production work while shipping authentication, payments, downloads and mapping features.', challenge:'Make the codebase easier to extend, test and maintain.', growth:'Architecture becomes part of the engineering instinct.', proof:'Primary Flutter POC · Clean Architecture · BLoC', kit:'BLoC · Clean Architecture · Payments · Maps'},
      {p:0.70, years:'Aug 2024 — Present', title:'Production became the <em>forge.</em>', body:'TheBlock demanded reliability under real pressure: Riverpod 3.0, real-time calling, screen sharing, media processing, Drift caching and mobile release continuity.', challenge:'200–300 defects, 50+ debt bottlenecks, and a calling migration from Agora to Stream.', growth:'Battle-tested production judgment.', proof:'200–300 defects resolved · 50+ debt bottlenecks removed', kit:'Riverpod 3.0 · Drift · Stream SDK · Media'},
      {p:0.84, years:'Current evolution', title:'Then mobile stopped being the <em>boundary.</em>', body:'The role expanded into FastAPI, WebSockets, Docker, Kubernetes, DigitalOcean, authentication/security work and AI-enhanced product experiences.', challenge:'Step outside the mobile comfort zone and own more of the system.', growth:'A multidimensional product engineer emerges.', proof:'FastAPI · WebSockets · Docker · Kubernetes', kit:'Backend APIs · Platform · Security · Deployments'},
      {p:0.94, years:'Now and next', title:'The view changes, not the <em>mission.</em>', body:'LangChain agents, deterministic AST-based SQL guardrails, an AI Email Agent and end-to-end product ownership mark the latest transformation — but the road keeps going, with larger systems and harder challenges ahead.', challenge:'Expand the range without losing reliability, taste or clarity of execution.', growth:'Emerald armor: mobile + backend + platform + AI + ownership.', proof:'4+ years of professional engineering', kit:'LangChain · AI guardrails · Product ownership'}
    ];

    const gemDefs = [
      {p:.11,label:'Ship',challenge:'First real clients',detail:'Build for people who depend on it',reward:'Shipping instinct',dark:false},
      {p:.18,label:'25K users',challenge:'Real users at scale',detail:'Cricwin grows beyond a side project',reward:'25K+ installs',dark:false},
      {p:.29,label:'MVP',challenge:'MVP pressure',detail:'Turn a fintech concept into something investable',reward:'Product judgment',dark:false},
      {p:.40,label:'Lead',challenge:'Lead a team',detail:'Own delivery beyond your own code',reward:'Leadership',dark:false},
      {p:.53,label:'Architecture',challenge:'Codebase complexity',detail:'Make growth maintainable, not fragile',reward:'Clean Architecture',dark:false},
      {p:.65,label:'Scale',challenge:'Production scale',detail:'Real-time calls, media, caching and releases',reward:'Production instincts',dark:true},
      {p:.73,label:'Reliability',challenge:'Reliability debt',detail:'200–300 defects and 50+ debt bottlenecks',reward:'Battle-tested judgment',dark:true},
      {p:.83,label:'Backend',challenge:'Beyond mobile',detail:'Own APIs, deployments and platform work',reward:'Full-stack range',dark:true},
      {p:.91,label:'AI guardrails',challenge:'Reliable AI',detail:'Constrain agents with deterministic boundaries',reward:'AI engineering',dark:true}
    ];
