    export const chapters = [
      {p:0.00, years:'2019 — 2022', title:'Computer Engineering with a <em>9.7 GPA.</em>', body:'Graduated in Computer Engineering with First Class Distinction. Built the fundamentals in programming, problem solving and software development.', challenge:'Education and engineering fundamentals.', growth:'First Class Distinction · 9.7 GPA final semester', proof:'Computer Engineering degree', kit:'Programming · Problem solving'},
      {p:0.14, years:'Dec 2021 — May 2022', title:'Freelance apps with <em>25K+ installs.</em>', body:'Built and shipped a three-app food delivery solution and Cricwin Live Guru. Worked directly with clients, deadlines, users and production feedback.', challenge:'Ship complete mobile products for real users.', growth:'Cricwin Live Guru reached 25K+ Google Play installs.', proof:'25K+ Google Play installs', kit:'Flutter · Dart · Firebase · REST APIs'},
      {p:0.28, years:'Feb 2022 — Sep 2022', title:'A fintech product from <em>concept to MVP.</em>', body:'At World of Wealth, developed a fintech mobile application for investment rounds and contributed to product decisions alongside implementation.', challenge:'Turn a product idea into a working MVP.', growth:'Concept-to-MVP delivery and product coordination.', proof:'Fintech mobile application · Concept → MVP', kit:'Flutter · Product coordination · Delivery'},
      {p:0.42, years:'Sep 2022 — Apr 2023', title:'Led a <em>two-developer</em> Flutter team.', body:'At KodeKrew, led two Flutter developers across news, astrology and instant-delivery applications while coordinating delivery and technical decisions.', challenge:'Coordinate a team and own delivery beyond individual code.', growth:'Technical leadership and broader system thinking.', proof:'Led a two-developer Flutter team', kit:'Live streaming · Places · Tracking · FCM'},
      {p:0.56, years:'Apr 2023 — Aug 2024', title:'Applied Clean Architecture in <em>production.</em>', body:'At Cropdata, became the primary Flutter point of contact and shipped authentication, payments, downloads and mapping features using BLoC and Clean Architecture.', challenge:'Keep a growing codebase maintainable and testable.', growth:'Production architecture and dependable feature delivery.', proof:'Primary Flutter POC · Clean Architecture · BLoC', kit:'BLoC · Payments · Maps · Downloads'},
      {p:0.70, years:'Aug 2024 — Present', title:'Resolved <em>200–300 defects</em> in production.', body:'At TheBlock, worked on Riverpod 3.0, real-time calling, screen sharing, media processing, Drift caching and mobile releases. Removed 50+ technical-debt bottlenecks and migrated calling from Agora to Stream.', challenge:'Improve reliability while continuing product delivery.', growth:'200–300 defects resolved · 50+ debt bottlenecks removed', proof:'Production mobile engineering at TheBlock', kit:'Riverpod 3.0 · Drift · Stream SDK · Media'},
      {p:0.84, years:'Current work', title:'Expanded from mobile to <em>backend and platform.</em>', body:'Added FastAPI, WebSockets, Docker, Kubernetes, DigitalOcean and authentication/security work to the mobile engineering toolkit.', challenge:'Own more of the system behind the mobile product.', growth:'Backend APIs, deployments and platform operations.', proof:'FastAPI · WebSockets · Docker · Kubernetes', kit:'Backend APIs · Platform · Security · Deployments'},
      {p:0.94, years:'Current work', title:'Building products across <em>mobile, backend and AI.</em>', body:'Current work includes LangChain agents, deterministic AST-based SQL guardrails, an AI Email Agent and end-to-end product ownership.', challenge:'Build useful AI features with clear, reliable boundaries.', growth:'Mobile + backend + platform + AI product engineering.', proof:'4+ years of professional engineering', kit:'LangChain · AI guardrails · Product ownership'}
    ];

    export const gemDefs = [
      {p:.11,label:'Freelance delivery',challenge:'Client applications',detail:'Built and shipped complete mobile products',reward:'Production delivery',dark:false},
      {p:.18,label:'25K+ installs',challenge:'Cricwin Live Guru',detail:'Reached 25K+ Google Play installs',reward:'25K+ installs',dark:false},
      {p:.29,label:'Fintech MVP',challenge:'World of Wealth',detail:'Moved a fintech app from concept to MVP',reward:'Product delivery',dark:false},
      {p:.40,label:'Team leadership',challenge:'KodeKrew',detail:'Led two Flutter developers',reward:'Technical leadership',dark:false},
      {p:.53,label:'Clean Architecture',challenge:'Cropdata',detail:'Applied BLoC and Clean Architecture in production',reward:'Maintainable systems',dark:false},
      {p:.65,label:'Production mobile',challenge:'TheBlock',detail:'Calling, media, caching and releases',reward:'Mobile reliability',dark:true},
      {p:.73,label:'Defect reduction',challenge:'TheBlock',detail:'Resolved 200–300 defects and 50+ bottlenecks',reward:'Reliability work',dark:true},
      {p:.83,label:'Backend and platform',challenge:'Current scope',detail:'FastAPI, WebSockets, Docker and Kubernetes',reward:'Full-stack range',dark:true},
      {p:.91,label:'AI engineering',challenge:'Current scope',detail:'Agents, SQL guardrails and AI email workflows',reward:'Reliable AI features',dark:true}
    ];
